name: Deploy to SSH Server

on:
  push:
    branches:
      - main  # Trigger deployment on push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest  # Runs on a GitHub-hosted Ubuntu runner

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3  # This checks out your repository so that we can deploy the code

    - name: Set up SSH
      run: |
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > private_key.pem
        chmod 600 private_key.pem  # Secure the private key file

    - name: Deploy to server
      run: |
        sudo apt-get update
        sudo apt-get install -y openssh-client

        ssh -i private_key.pem -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }} << 'EOF' #SSHKey not enabled yet
          cd ~/github_contents/software-engineering-team-beta || exit

          git pull || exit
          
          cp -r minigolf/* ~/public_html/minigolf/ || exit

          cd ~/public_html/minigolf/ || exit

          pid=$(lsof -t -i:9008) && if [ ! -z "$pid" ]; then kill -9 $pid; fi

          # Run python HTTP server in the background and redirect output to /dev/null
          nohup python -m http.server 9008 --directory ~/public_html/minigolf > /dev/null 2>&1 &

        EOF

    - name: Clean up SSH private key
      run: |
        rm -f private_key.pem
