name: Deploy to SSH Server

on:
  push:
    branches:
      - main  # Trigger deployment on push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest  # Runs on a GitHub-hosted Ubuntu runner

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3  # This checks out your repository so that we can deploy the code

    - name: Set up SSH
      run: |

        echo "${{ secrets.SSH_PRIVATE_KEY }}" > private_key.pem
        chmod 600 private_key.pem  # Secure the private key file

    - name: Deploy to server
      run: |
        sudo apt-get update
        sudo apt-get install -y openssh-client

        ssh -i private_key.pem -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }} << 'EOF' #SSHKey not enabled yet
        #ssh -p ${{ secrets.SSH_PASSWORD }} -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }} << 'EOF'
          cd ~/github_contents || exit

          git pull origin main || exit
          
          cp -r minigolf/* ~/public_html/ || exit
        EOF

    - name: Clean up SSH private key
      run: |
        rm -f private_key.pem
