name: PY-Script

on:
  push:
    branches:
      # - main
      - automated-testing
  pull_request:
    branches:
      # - main
      - automated-testing

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium webdriver-manager

      - name: Run tests
        run: |
          python minigolf/pytest.py
        env:
          DISPLAY: :99
